name: Build
on:
  push:
jobs:
  build-project:
    name: Build project
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        uses: threeal/cmake-action@v2.1.0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            build
