name: Build
on:
  push:
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        uses: threeal/cmake-action@v2.1.0
